---
title: "HTMN Presentation"
author: "Tiffany Jann"
date: "April 30, 2016"
output:
  ioslides_presentation:
    incremental: true
    transition: default
    fig_height: 2
    fig_width: 3
---


## CA Drought Data

```{r include=FALSE}
# Don't delete this chunk if you are using the DataComputing package
library(DataComputing)
library(lubridate)
library(reshape2)
library(ggthemes)
library(RColorBrewer)
library(grid)
library(scales)
library(car)
library(dplyr)
```


```{r include=FALSE}
timelapse <- "/Users/jann/stat133-spring2016/final_COUNTY2011-2016.csv"
timelapse <- timelapse  %>%
  read.file() %>%
  select(releaseDate, FIPS, NONE, D0, D1, D2, D3, D4)
```


```{r include=FALSE}
bins <- timelapse %>% mutate(D0=D0-D1, D1=D1-D2, D2=D2-D3, D3=D3-D4, releaseDate = floor_date(lubridate::ymd(releaseDate), "month"))

names(bins)[1] <- "Month"
```

```{r include=FALSE}
bins <- bins %>% mutate( FIPS_avg = (1*D0 + 2*D1 + 3*D2 + 4*D3 + 5*D4) /100 - 1) %>% group_by(Month, FIPS) %>% summarise(monthly_avg = round(mean(FIPS_avg)))
```

```{r include=FALSE}
drought_levels <- function(x) {
         (
          if (x==-1) {
            "No Drought (NONE)"
          } else if (x==0) {
            "Abnormally Dry (D0)"
          } else if (x==1) {
            "Moderate Drought (D1)"
          } else if (x==2) {
            "Severe Drought (D2)"
          } else if (x==3) {
            "Extreme Drought (D3)"
          } else
            "Exceptional Drought (D4)"
         )
}

bins <- bins %>% mutate(monthly_avg=sapply(monthly_avg,drought_levels))
```

```{r include=FALSE}
bins$monthly_avg <- factor(bins$monthly_avg, levels = c("No Drought (NONE)", "Abnormally Dry (D0)", "Moderate Drought (D1)", "Severe Drought (D2)", "Extreme Drought (D3)", "Exceptional Drought (D4)"))
```

```{r include=FALSE}
bins <- bins %>% select(Month, monthly_avg)  %>% arrange(Month)
```


```{r echo=FALSE}
bins %>% ggplot(aes(x=Month, fill=monthly_avg)) + geom_bar() + 
 scale_fill_manual("Drought Severity", values=c("#7baad8", "#fffc67", "orange", "darkorange3", "orangered3", "firebrick4")) + facet_wrap(~ monthly_avg) + ggtitle("Number of Counties in Each Drought Level") + ylab("# of Counties") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + theme(panel.background = element_rect(fill = "grey"),
        panel.background = element_rect(color = "black"),
        panel.grid.minor = element_line(linetype = "dotted"), 
        axis.title = element_text(size = rel(1.5)),
        axis.text = element_text(size = rel(1.0)),
        legend.text = element_text(size = rel(1.0)),
        plot.title = element_text(size = rel(2)),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  guides(fill=F)
```

```{r include=FALSE}
#install.packages("mapdata")
#install.packages("ggmap")
library(mapdata)
library(ggmap)

#data set that has drought by county

drought_severity <- "/Users/jann/stat133-spring2016/countydroughtseverity.csv"
drought_severity <- drought_severity%>%
  read.file()
drought_severity$county <- gsub(" County", "", drought_severity$county)
drought_severity$county <- sapply(drought_severity$county, tolower)

names(drought_severity)[names(drought_severity) == "county"] <- "subregion"
drought_severity <- data.frame(drought_severity)

#adding month and year column for later
drought_severity$releaseDate <- as.Date(drought_severity$releaseDate)
drought_severity$month <- months(drought_severity$releaseDate)
drought_severity$year <- year(ymd(drought_severity$releaseDate)) 

```


```{r include=FALSE}
#narrow version of drought_severity 
#taking the average for each month for each category of severity for simplicity

tidy_severity <- drought_severity%>%
  gather(key = category, value = value, NONE, D0, D1, D2, D3, D4)%>%
  select(subregion, month, year, category, value, FIPS)%>%
    group_by(month, year, subregion, category)%>%
  summarise(ave_value = mean(value))

#just making sure everything is in the correct format for ease of plotting
tidy_severity <- data.frame(tidy_severity)
tidy_severity$year <- as.numeric(tidy_severity$year)


#coordinates for the california counties
CAcounties <- map_data('county')%>%
  filter(region == "california")
CAcounties <- data.frame(CAcounties)


#merge drought information with coordinates for each county
CAcountiesvalues <- CAcounties%>%
  right_join(tidy_severity, by = "subregion")


#creating levels for mapping later
CAcountiesvalues$category <- factor(CAcountiesvalues$category, levels = c("D4", "D3", "D2", "D1", "D0", "NONE"))

CAcountiesvalues$month <- factor(CAcountiesvalues$month, levels = c("January", "February", "March", "April", "May","June", "July", "August","September", "October", "November","December"))

```



```{r include=FALSE}

#okay so this makes the really large grid with many maps, may just use this as an overview, then take pieces from it?

CAcountiesvalues%>% 
  ggplot() + 
  geom_polygon(aes (x = long, y = lat, group = group, fill = ave_value), colour = "white", size = 0.02)+ scale_fill_gradient(low = "yellow", high = "red") + 
  facet_grid(category ~ year) +
  labs(x = "Year", y = "Drought Severity", title = "Drought Severity vs Year") +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),axis.text.y=element_blank(),axis.ticks=element_blank())
```


```{r include=FALSE}
timelapse <- "/Users/jann/stat133-spring2016/final_COUNTY2011-2016.csv"
timelapse <- timelapse  %>%
  read.file() %>%
  select(releaseDate, county, FIPS, NONE, D0, D1, D2, D3, D4)
head(timelapse)
```

```{r include=FALSE}
bins <- timelapse %>% mutate(D0=D0-D1, D1=D1-D2, D2=D2-D3, D3=D3-D4)

bins$releaseDate <- as.Date(bins$releaseDate)
bins$month <- months(bins$releaseDate)
bins$year <- year(ymd(bins$releaseDate)) 

head(bins)
```

```{r include=FALSE}
bins <- bins %>% mutate( FIPS_avg = (1*D0 + 2*D1 + 3*D2 + 4*D3 + 5*D4) /100 - 1) %>% group_by(month, year, FIPS, county) %>% summarise(monthly_avg = round(mean(FIPS_avg)))

bins$county <- gsub(" County", "", bins$county)
bins$county <- sapply(bins$county, tolower)

names(bins)[names(bins) == "county"] <- "subregion"
bins<- data.frame(bins)

head(bins)
```

```{r include=FALSE}
drought_levels <- function(x) {
         (
          if (x==-1) {
            "No Drought (NONE)"
          } else if (x==0) {
            "Abnormally Dry (D0)"
          } else if (x==1) {
            "Moderate Drought (D1)"
          } else if (x==2) {
            "Severe Drought (D2)"
          } else if (x==3) {
            "Extreme Drought (D3)"
          } else
            "Exceptional Drought (D4)"
         )
}

bins <- bins %>% mutate(monthly_avg=sapply(monthly_avg,drought_levels))
head(bins)

```

```{r include=FALSE}
binscounties <- bins%>%
  right_join(CAcounties, by = c("subregion"))

```

```{r include=FALSE}
binscounties$month <- factor(binscounties$month, levels = c("January", "February", "March", "April", "May","June", "July", "August","September", "October", "November","December"))

binscounties$monthly_avg <- factor(binscounties$monthly_avg, levels = c("No Drought (NONE)", "Abnormally Dry (D0)", "Moderate Drought (D1)", "Severe Drought (D2)", "Extreme Drought (D3)", "Exceptional Drought (D4)"))
```

```{r include=FALSE}
binscounties <- binscounties %>%
  group_by(year)%>%
  arrange(month)%>%
  mutate(completedate = (paste(month, year)))

head(binscounties) 

```

```{r include=FALSE}
months <- c("January", "February", "March", "April", "May","June", "July", "August","September", "October", "November","December")

months <- rep(months, times = 17)

years <- rep(2000:2016, each = 12)

monthsyears <- paste(months, years)

monthsyears <- monthsyears[1:(length(monthsyears) - 8)]

monthsyears

binscounties$completedate <- factor(levels = c(monthsyears), binscounties$completedate)


binscounties$completedate <- as.factor( binscounties$completedate)

binscounties <- data.frame(binscounties)
```



```{r, echo=FALSE}
binscounties%>%
  filter(year >= 2011)%>%
  ggplot() + 
  geom_polygon(aes (x = long, y = lat, group = group, fill = monthly_avg), colour = "white", size = 0.02)+
  facet_wrap(~completedate, ncol = 12, drop = TRUE) +
  labs(x = "Month", y = "Year", title = "Drought Severity in California from 2011 to Present") +
  theme(axis.line=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        panel.grid.major = element_blank(),	
        panel.grid.minor = element_blank(), 
        legend.key = element_rect(colour = "black"),
        plot.background = element_rect(colour = "grey"),
        panel.background = element_rect(fill = "grey"),
        panel.background = element_rect(color = "black"),
        panel.grid.minor = element_line(linetype = "dotted"), 
        axis.title = element_text(size = rel(1.5)),
        legend.text = element_text(size = rel(1.0)),
        plot.title = element_text(size = rel(2))
        ) + 
  theme(axis.line=element_blank(),axis.text.x=element_blank(),axis.text.y=element_blank(),axis.ticks=element_blank()) + 
 scale_fill_manual("Drought Severity", values=c("#7baad8", "#fffc67", "orange", "darkorange3", "orangered3", "firebrick4"))

```

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Code and Output

```{r}
summary(cars)
```

## Slide with Plot

```{r, echo=FALSE}
plot(cars)
```

